env:
  SYMFONY_ENV=test

language: php

services:
  - mysql

php:
    - 7.0
    - 7.1

before_install:
 - mysql -e 'create database gamespoint;'

install:
  - travis_retry composer selfupdate
  - travis_retry composer install --no-interaction --prefer-source

script:
  - phpunit
